/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounts.index"];
        put?: never;
        post: operations["accounts.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounts.show"];
        put?: never;
        post?: never;
        delete: operations["accounts.destroy"];
        options?: never;
        head?: never;
        patch: operations["account.update"];
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.authStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories.index"];
        put?: never;
        post: operations["categories.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories.show"];
        put?: never;
        post?: never;
        delete: operations["categories.destroy"];
        options?: never;
        head?: never;
        patch: operations["category.update"];
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me.update"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Os dois casos abaixo são decididos em EnsureRegistrationAllowed (antes
         *     deste método rodar), então o Scramble não os infere do corpo: ficam
         *     documentados manualmente para bater com o middleware
         */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session.destroy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tags.index"];
        put?: never;
        post: operations["tags.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["tags.destroy"];
        options?: never;
        head?: never;
        patch: operations["tag.update"];
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions.index"];
        put?: never;
        post: operations["transactions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transaction}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions.show"];
        put?: never;
        post?: never;
        delete: operations["transactions.destroy"];
        options?: never;
        head?: never;
        patch: operations["transaction.update"];
        trace?: never;
    };
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transfer.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/{transfer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transfer.show"];
        put?: never;
        post?: never;
        delete: operations["transfer.destroy"];
        options?: never;
        head?: never;
        patch: operations["transfer.update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResource */
        AccountResource: {
            id: number;
            name: string;
            type: components["schemas"]["AccountType"];
            currency: string;
            opening_balance: number;
            balance: number;
            color: string | null;
            icon: string | null;
            is_archived: boolean;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "checking" | "savings" | "cash";
        /**
         * CategoryKind
         * @enum {string}
         */
        CategoryKind: "income" | "expense";
        /** CategoryResource */
        CategoryResource: {
            id: number;
            parent_id: number | null;
            name: string;
            kind: components["schemas"]["CategoryKind"];
            icon: string | null;
            color: string | null;
            is_transfer: boolean;
            is_transfer_effective: boolean;
            is_archived: boolean;
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "in" | "out";
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** SaveTagRequest */
        SaveTagRequest: {
            name: string;
            color?: string | null;
        };
        /** StoreAccountRequest */
        StoreAccountRequest: {
            name: string;
            type: components["schemas"]["AccountType"];
            currency?: string;
            opening_balance?: number;
            color?: string | null;
            icon?: string | null;
        };
        /** StoreCategoryRequest */
        StoreCategoryRequest: {
            name: string;
            kind: components["schemas"]["CategoryKind"];
            parent_id?: number | null;
            icon?: string | null;
            color?: string | null;
            is_transfer?: boolean;
        };
        /** StoreTransactionRequest */
        StoreTransactionRequest: {
            account_id: number;
            /** Format: date */
            date: string;
            amount: number;
            direction: components["schemas"]["Direction"];
            description: string;
            category_id?: number | null;
            notes?: string | null;
            payee?: string | null;
            is_ignored?: boolean;
            tag_ids?: number[];
        };
        /** StoreTransferRequest */
        StoreTransferRequest: {
            from_account_id: number;
            to_account_id: number;
            /** Format: date */
            date: string;
            amount: number;
            description: string;
            notes?: string | null;
        };
        /** TagResource */
        TagResource: {
            id: number;
            name: string;
            color: string | null;
        };
        /** TransactionResource */
        TransactionResource: {
            id: number;
            account_id: number;
            account?: {
                id: number;
                name: string;
                type: components["schemas"]["AccountType"];
                color: string | null;
                icon: string | null;
            };
            date: string;
            amount: number;
            direction: components["schemas"]["Direction"];
            currency: string;
            description: string;
            original_description: string;
            description_locked: boolean;
            notes: string | null;
            payee: string | null;
            category_id: number | null;
            category?: {
                id: number;
                parent_id: number | null;
                name: string;
                icon: string | null;
                color: string | null;
                is_transfer: boolean;
                is_transfer_effective: boolean;
            } | null;
            tags?: components["schemas"]["TagResource"][];
            status: components["schemas"]["TransactionStatus"];
            source: components["schemas"]["TransactionSource"];
            categorized_by: string | null;
            is_ignored: boolean;
            transfer_id: string | null;
        };
        /**
         * TransactionSource
         * @enum {string}
         */
        TransactionSource: "manual" | "pluggy" | "csv" | "ofx" | "recurrence" | "installment";
        /**
         * TransactionStatus
         * @enum {string}
         */
        TransactionStatus: "posted" | "projected" | "pending";
        /** TransferResource */
        TransferResource: {
            transfer_id: string;
            date: string;
            amount: number;
            description: string;
            notes: string | null;
            from: components["schemas"]["TransactionResource"];
            to: components["schemas"]["TransactionResource"];
        };
        /**
         * UpdateAccountRequest
         * @description `currency` não é editável: mudar a moeda de uma conta com histórico
         *     corromperia os valores. Campos fora das regras são ignorados.
         */
        UpdateAccountRequest: {
            name?: string;
            type?: components["schemas"]["AccountType"];
            opening_balance?: number;
            color?: string | null;
            icon?: string | null;
            is_archived?: boolean;
        };
        /** UpdateCategoryRequest */
        UpdateCategoryRequest: {
            name?: string;
            parent_id?: number | null;
            icon?: string | null;
            color?: string | null;
            is_transfer?: boolean;
            is_archived?: boolean;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            name?: string;
            password?: string;
            current_password?: string | null;
            password_confirmation?: string;
        };
        /** UpdateTransactionRequest */
        UpdateTransactionRequest: {
            account_id?: number;
            /** Format: date */
            date?: string;
            amount?: number;
            direction?: components["schemas"]["Direction"];
            description?: string;
            category_id?: number | null;
            notes?: string | null;
            payee?: string | null;
            is_ignored?: boolean;
            tag_ids?: number[];
        };
        /** UpdateTransferRequest */
        UpdateTransferRequest: {
            from_account_id?: number;
            to_account_id?: number;
            /** Format: date */
            date?: string;
            amount?: number;
            description?: string;
            notes?: string | null;
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            avatar: string | null;
            has_password: boolean;
            google_linked: boolean;
            /**
             * @description Configuração da instância (ainda não é por usuário); fica aqui para o
             *     frontend não fixar 'BRL' ao decidir quando mostrar a moeda de uma conta.
             */
            primary_currency: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "accounts.index": {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `AccountResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccountResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "accounts.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreAccountRequest"];
            };
        };
        responses: {
            /** @description `AccountResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccountResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "accounts.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The account ID */
                account: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AccountResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccountResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "accounts.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The account ID */
                account: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "account_has_transactions";
                        message: string;
                    };
                };
            };
        };
    };
    "account.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The account ID */
                account: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description `AccountResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccountResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.authStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            google_login_enabled: boolean;
                            registration_enabled: boolean;
                        };
                    };
                };
            };
        };
    };
    "categories.index": {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `CategoryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "categories.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCategoryRequest"];
            };
        };
        responses: {
            /** @description `CategoryResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "categories.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CategoryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "categories.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "category_has_children";
                        message: string;
                    };
                };
            };
        };
    };
    "category.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The category ID */
                category: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description `CategoryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.dashboard": {
        parameters: {
            query?: {
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            month: string;
                            currency: string;
                            total_balance: number;
                            balance_date: string;
                            accounts: {
                                id: number;
                                name: string;
                                type: components["schemas"]["AccountType"];
                                currency: string;
                                color: string | null;
                                icon: string | null;
                                balance: number;
                            }[];
                            income: number;
                            expense: number;
                            net: number;
                            top_categories: {
                                category_id: number | null;
                                name: string | "Sem categoria";
                                icon: string | null;
                                color: string | null;
                                amount: number;
                            }[];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "me.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "me.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            /** @description session_required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "session_required";
                        message: string;
                    };
                };
            };
            /** @description registration_closed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "registration_closed";
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "session.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "session_required";
                        /** @constant */
                        message: "Login só é aceito a partir do frontend (origem stateful).";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "session.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tags.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `TagResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TagResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tags.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTagRequest"];
            };
        };
        responses: {
            /** @description `TagResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TagResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "tags.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tag ID */
                tag: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "tag.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tag ID */
                tag: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTagRequest"];
            };
        };
        responses: {
            /** @description `TagResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TagResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "transactions.index": {
        parameters: {
            query?: {
                account_id?: number;
                category_id?: number;
                tag_id?: number;
                from?: string;
                to?: string;
                status?: components["schemas"]["TransactionStatus"];
                direction?: components["schemas"]["Direction"];
                search?: string;
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TransactionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TransactionResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description The "cursor" that points to the next set of items. */
                            next_cursor: string | null;
                            /** @description The "cursor" that points to the previous set of items. */
                            prev_cursor: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "transactions.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreTransactionRequest"];
            };
        };
        responses: {
            /** @description `TransactionResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransactionResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "transactions.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The transaction ID */
                transaction: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `TransactionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransactionResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "transactions.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The transaction ID */
                transaction: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "transaction.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The transaction ID */
                transaction: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description `TransactionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransactionResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "transfer_leg_locked";
                        message: string;
                    } | {
                        /** @enum {string} */
                        code: "transaction_currency_mismatch";
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "transfer.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreTransferRequest"];
            };
        };
        responses: {
            /** @description `TransferResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransferResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "transfer_same_account";
                        message: string;
                    } | {
                        /** @enum {string} */
                        code: "transfer_currency_mismatch";
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "transfer.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `TransferResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransferResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "transfer.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "transfer.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTransferRequest"];
            };
        };
        responses: {
            /** @description `TransferResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransferResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "transfer_same_account";
                        message: string;
                    } | {
                        /** @enum {string} */
                        code: "transfer_currency_mismatch";
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
