// Conjunto curado de ícones lucide para categorias. Imports estáticos de propósito:
// `lucide-react/dynamic` fazia o bundle principal saltar de ~220KB para ~500KB e gerava
// ~1860 chunks (um por ícone da biblioteca inteira). Aqui só entram os ícones que o backend
// semeia mais alguns extras úteis; qualquer outro nome cai no fallback "tag" do CategoryIcon.
import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  Coins,
  CirclePlus,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Ellipsis,
  FileText,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  type LucideIcon,
  Music,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TrainFront,
  TrendingUp,
  Tv,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // Seedados pelo backend.
  house: House,
  utensils: Utensils,
  car: Car,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'party-popper': PartyPopper,
  'shopping-bag': ShoppingBag,
  landmark: Landmark,
  'paw-print': PawPrint,
  ellipsis: Ellipsis,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  'undo-2': Undo2,
  'circle-plus': CirclePlus,
  'arrow-left-right': ArrowLeftRight,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  tag: Tag,
  // Extras úteis.
  'shopping-cart': ShoppingCart,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  plane: Plane,
  bike: Bike,
  tv: Tv,
  music: Music,
  'gamepad-2': Gamepad2,
  dumbbell: Dumbbell,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  gift: Gift,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  shirt: Shirt,
  scissors: Scissors,
  wrench: Wrench,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  smartphone: Smartphone,
  'book-open': BookOpen,
  film: Film,
  receipt: Receipt,
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  'hand-coins': HandCoins,
  'building-2': Building2,
  dog: Dog,
  sparkles: Sparkles,
  percent: Percent,
  'file-text': FileText,
}

export const categoryIconNames = Object.keys(CATEGORY_ICONS)

// Rótulos em português para cada ícone, usados em aria-label de seletores.
export const CATEGORY_ICON_LABELS: Record<string, string> = {
  house: 'Casa',
  utensils: 'Talheres',
  car: 'Carro',
  'heart-pulse': 'Saúde',
  'graduation-cap': 'Educação',
  'party-popper': 'Festa',
  'shopping-bag': 'Compras',
  landmark: 'Banco',
  'paw-print': 'Pet',
  ellipsis: 'Outros',
  briefcase: 'Trabalho',
  laptop: 'Tecnologia',
  'trending-up': 'Investimento',
  'undo-2': 'Reembolso',
  'circle-plus': 'Receita',
  'arrow-left-right': 'Transferência',
  'credit-card': 'Cartão',
  'piggy-bank': 'Economia',
  tag: 'Etiqueta',
  'shopping-cart': 'Supermercado',
  fuel: 'Combustível',
  bus: 'Ônibus',
  'train-front': 'Trem',
  plane: 'Viagem',
  bike: 'Bicicleta',
  tv: 'TV',
  music: 'Música',
  'gamepad-2': 'Jogos',
  dumbbell: 'Academia',
  pill: 'Remédio',
  stethoscope: 'Médico',
  baby: 'Bebê',
  gift: 'Presente',
  coffee: 'Café',
  pizza: 'Pizza',
  beer: 'Bar',
  shirt: 'Roupas',
  scissors: 'Cabelo',
  wrench: 'Manutenção',
  zap: 'Energia',
  droplet: 'Água',
  wifi: 'Internet',
  smartphone: 'Celular',
  'book-open': 'Livros',
  film: 'Cinema',
  receipt: 'Recibo',
  wallet: 'Carteira',
  banknote: 'Dinheiro',
  coins: 'Moedas',
  'hand-coins': 'Doação',
  'building-2': 'Imóvel',
  dog: 'Cachorro',
  sparkles: 'Beleza',
  percent: 'Taxas',
  'file-text': 'Documentos',
}
