// Conjunto curado de ícones lucide para categorias. Imports estáticos de propósito:
// `lucide-react/dynamic` fazia o bundle principal saltar de ~220KB para ~500KB e gerava
// ~1860 chunks (um por ícone da biblioteca inteira). Aqui só entram os ícones que o backend
// semeia mais alguns extras úteis; qualquer outro nome cai no fallback "tag" do CategoryIcon.
import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  Coins,
  CirclePlus,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Ellipsis,
  FileText,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  type LucideIcon,
  Music,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TrainFront,
  TrendingUp,
  Tv,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // Seedados pelo backend.
  house: House,
  utensils: Utensils,
  car: Car,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'party-popper': PartyPopper,
  'shopping-bag': ShoppingBag,
  landmark: Landmark,
  'paw-print': PawPrint,
  ellipsis: Ellipsis,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  'undo-2': Undo2,
  'circle-plus': CirclePlus,
  'arrow-left-right': ArrowLeftRight,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  tag: Tag,
  // Extras úteis.
  'shopping-cart': ShoppingCart,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  plane: Plane,
  bike: Bike,
  tv: Tv,
  music: Music,
  'gamepad-2': Gamepad2,
  dumbbell: Dumbbell,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  gift: Gift,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  shirt: Shirt,
  scissors: Scissors,
  wrench: Wrench,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  smartphone: Smartphone,
  'book-open': BookOpen,
  film: Film,
  receipt: Receipt,
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  'hand-coins': HandCoins,
  'building-2': Building2,
  dog: Dog,
  sparkles: Sparkles,
  percent: Percent,
  'file-text': FileText,
}

export const categoryIconNames = Object.keys(CATEGORY_ICONS)
